dataset_name: 'soygene4'
dataset_root_path: '../../data/soygene'
df_train: 'train_val_4.csv'
df_trainval: train_val_4.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: 'images'
folder_val: 'images'
folder_test: 'images'
df_classid_classname: False
